# айдишник int

STATEMENT_ADMIN =  #здорик
STATEMENT_REG_ADMIN =  #эберляйн 
APPLICATION_ADMIN = 6114027668

STATEMENT_ACCESS = []
TIMETABLE_ACCESS = []
MAILING_ACCESS = []
EVENT_ACCESS = []
GENERATE_ACCESS = []

ALL_ADMINS = set(TIMETABLE_ACCESS + MAILING_ACCESS + EVENT_ACCESS + GENERATE_ACCESS)